Promote staging to prod
nounsDAO/nouns-monorepo pull request #337
Opened 2022-01-20 15:35 UTC by cryptoseneca

This PR pushes the updated navigation bar feature to production:
- #322 
- #335

2022-01-20 16:26 UTC, gitblamecarrot requested changes
There's a regression in the Fortmatic key that should block promotion to prod.

Other notes are just smells.

2022-01-20 16:26 UTC, gitblamecarrot commented on packages/nouns-webapp/src/components/NavBarTreasury/index.tsx
> +  switch (treasuryStyle) {
Smell here: effectively duplicate code translating a `NavBarButtonStyle` to classes with `packages/nouns-webapp/src/components/NavBarButton/index.tsx`. Should be addressable with a single helper and a common module.

Doesn't need to block promotion but should be addressed later.

2022-01-20 16:26 UTC, gitblamecarrot commented on packages/nouns-webapp/src/components/NavWallet/index.tsx
> +              usePickByState(
"Helper functions that contain hooks as parameters to functions in props" is a mouthful, which is a good sign it's probably a smell as well.

Also not blocking but could use some attention.

2022-01-20 16:26 UTC, gitblamecarrot commented on packages/nouns-webapp/src/components/WalletConnectModal/index.tsx
> +            apiKey: 'pk_test_FB5E5C15F2EC5AE6',
Regression to a test Fortmatic key, this one is blocking.

2022-01-29 16:21 UTC, closed without merging

2022-01-29 16:22 UTC, cryptoseneca commented
Closed due to #308 including updates to nav bar. dev's review comments are now in #343