[WIP] Updated proposal page
nounsDAO/nouns-monorepo pull request #379
Opened 2022-02-24 18:31 UTC by bcjgit

2022-03-01 16:42 UTC, cryptoseneca reviewed
Great job @bcjgit. Massive upgrade to the vote page here. Few things UX-wise:

## Noun card on mobile
The `NounImageVoteTable` feels like overkill on mobile. Maybe we can try reducing the space each voting card takes to have it each be 33% of one row?

![mobile](https://user-images.githubusercontent.com/85328329/156209036-04114667-1510-4e28-b0da-5c413bcadd4c.png)

## Noun card on desktop
- Spacing feels off
<img width="300" alt="Screen Shot 2022-03-01 at 10 56 24 AM" src="https://user-images.githubusercontent.com/85328329/156209943-3b3b2076-3f18-4d6b-b0a2-952f09254bf6.png">

## Error alert
- Copy feels too big, let's make it feel more cohesive with error message.
- Once error shows up, I can’t “reset state”. That is, after i dismiss the error alert and click “Submit vote” again, I get the same state. This happened when attempting to vote again (obvious error) but in production it might be a simple failed tx which would indeed require the user to submit again. 

<img width="521" alt="Screen Shot 2022-03-01 at 10 46 26 AM" src="https://user-images.githubusercontent.com/85328329/156209250-c16388e8-62ee-4fdf-a99e-78b2ec716f6c.png">

2022-03-01 16:42 UTC, cryptoseneca commented on packages/nouns-webapp/src/components/NounImageVoteTable/index.tsx
> +const NOUNS_PER_VOTE_CARD = 15;
nit: let's add `DESKTOP` to var name so we know that it's meant to be 15 on desktop only

2022-03-01 17:29 UTC, lastpunk9999 commented
1) Implement scrolling or another solution to see all the Nouns. It feels strange to see only the first 15 Nouns who voted when the count is usually much higher.
2) Use the proposal id as a seed to randomly shuffle the order of Nouns. I notice that Nounders Nouns most frequently show in the top 15 (and take up a lot of the slots) because we tend to vote at the beginning of the active period. If the Noun images were randomized it would allow more Nouns to be in the top 15.

2022-03-03 02:42 UTC, lastpunk9999 commented
> 2. Use the proposal id as a seed to randomly shuffle the order of Nouns. 
Hacked some code to make this work: https://gist.github.com/lastpunk9999/5296a3ec8a41688e12b94f3c6d18cd62

2022-03-05 09:06 UTC, bcjgit commented
^^ Changes should address all feedback except for:

1. Scrolling Nouns (working on a solution here)
2. Making the vote counts 33% on mobile (open to doing it but went for the 1st of the suggested options where we just omit the Noun vote images on mobile)

2022-03-05 13:43 UTC, cryptoseneca reviewed
Looks good! A few things:
- Shuffling of the nouns doesn't seem to be working.
- Can we go for 33% card for vote counts on mobile? While first option is better than full display, the six rows do take up too much real estate on mobile. Cutting this in half would make the whole feel more compact. 

### Alerts
While the decrease in fort size helps with the error alert, it still feels off. It might be due to the fact that the content ("well this is awkward") uses the same font as the title ("proposal #41") and is more or less still the same size. More broadly, I think it's more of a styling issue with the bootstrap alert component. What do you think about using our own `Modal` for both voting and alerts? It already comes with spacing/fonts/styling and plays well with mobile.

![eg](https://user-images.githubusercontent.com/85328329/156887693-66cc443a-ac25-40a5-a5ac-dc4fa3353e3e.png)

2022-03-07 14:50 UTC, lastpunk9999 commented
> * Shuffling of the nouns doesn't seem to be working

I think it works on my side @cryptoseneca 

On `Prop 39` without shuffling all Nounder Nouns are sequentially clustered together (Gnome/Noun 0, Shoe/Noun 10, etc)
![image](https://user-images.githubusercontent.com/83411264/157056816-ee4fd62c-e941-4013-b417-acff51cd6a7f.png)

With shuffling they are distributed
![image](https://user-images.githubusercontent.com/83411264/157056987-c91853cf-7292-449c-b835-d9d27ee80b17.png)

2022-03-07 14:56 UTC, lastpunk9999 requested changes
@bcjgit I'm noticing a bug: when clicking on a Noun image in the proposal page, the app does not navigate to the correct Noun, but the last Noun that was viewed (eg: if I start on the current auction page, then navigate to a proposal, clicking a Noun brings me back to the current auction page)

2022-03-07 16:17 UTC, bcjgit commented
> @bcjgit I'm noticing a bug: when clicking on a Noun image in the proposal page, the app does not navigate to the correct Noun, but the last Noun that was viewed (eg: if I start on the current auction page, then navigate to a proposal, clicking a Noun brings me back to the current auction page)

Good catch. I think I know why that is. Fixing now...

2022-03-07 18:39 UTC, lastpunk9999 commented
> 1. Scrolling Nouns (working on a solution here)

@bcjgit I wonder if scrolling within an element is awkward and maybe a modal would be better or easier?

2022-03-07 19:12 UTC, bcjgit commented
@lastpunk9999 

I fixed the issue you mentioned where noun images were not linking correctly. Per our discussion on Discord, I'll punt Noun scrolling / modal etc. to a follow up task (issue: https://github.com/nounsDAO/nouns-monorepo/issues/385)

@cryptoseneca 
1. Mobile vote count cards are not 33% per your comment
2. I migrated the vote modal to use the Nouns custom modal vs bootstrap modal
3. I've decrease the text size of the success / failure states in the vote modal to match with the modal style vs being large font + brand text 
4. As both 9999 and I do see Nouns shuffling  I took no action on that point ... let me know if it still isn't working for you

2022-03-08 15:08 UTC, lastpunk9999 approved these changes

2022-03-09 14:56 UTC, cryptoseneca commented
> @lastpunk9999
> 
> I fixed the issue you mentioned where noun images were not linking correctly. Per our discussion on Discord, I'll punt Noun scrolling / modal etc. to a follow up task (issue: #385)
> 
> @cryptoseneca
> 
> 1. Mobile vote count cards are not 33% per your comment
> 2. I migrated the vote modal to use the Nouns custom modal vs bootstrap modal
> 3. I've decrease the text size of the success / failure states in the vote modal to match with the modal style vs being large font + brand text
> 4. As both 9999 and I do see Nouns shuffling  I took no action on that point ... let me know if it still isn't working for you

my mistake, i thought shuffling was supposed to happen on each reload. i now see it's on a per proposal basis.

> @lastpunk9999
> 
> I fixed the issue you mentioned where noun images were not linking correctly. Per our discussion on Discord, I'll punt Noun scrolling / modal etc. to a follow up task (issue: #385)
> 
> @cryptoseneca
> 
> 1. Mobile vote count cards are not 33% per your comment
> 2. I migrated the vote modal to use the Nouns custom modal vs bootstrap modal
> 3. I've decrease the text size of the success / failure states in the vote modal to match with the modal style vs being large font + brand text
> 4. As both 9999 and I do see Nouns shuffling  I took no action on that point ... let me know if it still isn't working for you

my mistake. i thought shuffling was supposed to happen on each reload of page. i now see it's per proposal.

2022-03-09 14:56 UTC, cryptoseneca approved these changes

2022-03-09 21:41 UTC, cryptoseneca approved these changes

2022-03-09 21:59 UTC, merged